#model parameters
baseline: False
data: "cifar"

model: 
 type: "Conv8"
 masking_method: "fixed"
 tanh_th: .4
 k_cnn: .25
 k_dense: .25
 dynamic_scaling_cnn: False
 dynamic_scaling_dense: False
 width_multiplier: 1.
 use_dropout: False

path_weights: "./weights/Conv8/weight/signed_constant/elu_scaled/"
path_masks: "./weights/Conv8/mask/uniform/xavier/"


#init parameters weights
#init_distribution_w: "uniform"
#init_constant_w: -2
#init_sigma_w: -8
#init_factor_w: 1./np.sqrt(3)

#init parameters mask
#init_distribution_m: "uniform"
#init_constant_m: -2
#init_sigma_m: -8
#init_factor_m: 1./np.sqrt(3)

#optimizer parameters
optimizer:
 type: "sgdw"
 lr_scheduler: "exponential_decay" #exponential_decay, None
 lr: .05
 weight_decay: 5e-4
 momentum: .9
 nesterov: True
 #in case rms_prop is used
 centered: True

training:
 epochs: 100
 no_experiments: 50 #max: 50
