#model parameters
baseline: True
data: "cifar"

model: 
 type: "Conv4"
 masking_method: "fixed" 
 tanh_th: .4
 k_cnn: .25
 k_dense: .25
 dynamic_scaling_cnn: False
 dynamic_scaling_dense: False
 width_multiplier: 1.
 use_dropout: False

path_weights: "./weights/Conv4/weight/uniform/elu/"
#path_masks: "./weights/Conv4/mask/uniform/xavier/"

#init parameters weights
#init_distribution_w: "uniform"
#init_constant_w: -2
#init_sigma_w: -8
#init_factor_w: 1./np.sqrt(3)

#init parameters mask
#init_distribution_m: "uniform"
#init_constant_m: -2
#init_sigma_m: -8
#init_factor_m: 1./np.sqrt(3)

#optimizer parameters
optimizer:
 type: "sgdw"
 lr_scheduler: "exponential_decay" #exponential_decay, None
 decay_steps: 5
 lr: .008
 weight_decay: 7e-4
 momentum: .9
 nesterov: True
 #in case rms_prop is used
 centered: True

training:
 epochs: 50
 no_experiments: 50 #max: 50
