#model parameters
baseline: False
data: "mnist"

model: 
 type: "FCN"
 masking_method: "variable" #variable == no score (ZHOU), fixed == score (RAMARUNJAN)
 tanh_th: .4
 k_cnn: .25
 k_dense: .5
 dynamic_scaling_cnn: False
 dynamic_scaling_dense: False
 width_multiplier: 1.
 use_dropout: False

path_weights: "./path/to/weight"
path_masks: "./path/to/mask"

#optimizer parameters
optimizer:
 type: "sgdw"
 lr_scheduler: "exponential_decay" #exponential_decay, None
 lr: .05
 weight_decay: 5e-4
 momentum: .9
 nesterov: True
 #in case rms_prop is used
 centered: True

training:
 epochs: 100
 no_experiments: 50 #max: 50
